// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_61CuJZctTdiRJ-SlbTcsKIc6rMTzxvA',
    appId: '1:291416133834:web:ac3e5fac6a6f04f0d2a433',
    messagingSenderId: '291416133834',
    projectId: 'vidyanchild-lms',
    authDomain: 'vidyanchild-lms.firebaseapp.com',
    storageBucket: 'vidyanchild-lms.firebasestorage.app',
    measurementId: 'G-BS4Q47RDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSg-t_Jro36aPcO69zTJzYjMNhvx21rk',
    appId: '1:291416133834:android:a07d1d5059781bfbd2a433',
    messagingSenderId: '291416133834',
    projectId: 'vidyanchild-lms',
    storageBucket: 'vidyanchild-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLpoE05jJUoh00y9Hg061rIeHDgoVZbI',
    appId: '1:291416133834:ios:dbd2eb019699b71bd2a433',
    messagingSenderId: '291416133834',
    projectId: 'vidyanchild-lms',
    storageBucket: 'vidyanchild-lms.firebasestorage.app',
    iosBundleId: 'com.example.lmsProject',
  );
}
